description = "cflinuxfs3 base image with buildpacks for Java, .NET, NodeJS, Golang, PHP, HTTPD and NGINX"

[[order]]
group = [

### Order is strictly enforced
  { id = "paketo-buildpacks/bellsoft-liberica",          optional = true },
  { id = "paketo-buildpacks/build-system",               optional = true },

### Order determines precedence
  { id = "paketo-buildpacks/executable-jar",             optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              optional = true },
  { id = "paketo-buildpacks/spring-boot",                optional = true },
  { id = "paketo-buildpacks/dist-zip",                   optional = true },
  { id = "paketo-buildpacks/procfile",                   optional = true },

### Order does not matter
  { id = "paketo-buildpacks/azure-application-insights", optional = true },
  { id = "paketo-buildpacks/debug",                      optional = true },
  { id = "paketo-buildpacks/jmx",                        optional = true },

### Order is strictly enforced
  { id = "paketo-buildpacks/encrypt-at-rest",            optional = true },
]

[[order]]
group = [
  { id = "paketo-buildpacks/nodejs" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/go" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/dotnet-core" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/php" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/httpd" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/nginx" },
]

[[order]]
group = [
  { id = "paketo-buildpacks/procfile" },
]
